plugins {
    id 'com.android.application'
}

android {
    namespace 'net.eximpoglobal.app'
    compileSdk 35

    defaultConfig {
        applicationId "net.eximpoglobal.app"
        minSdk 24
        targetSdk 35
        versionCode 5
        versionName "1.4"
    }

    signingConfigs {
        release {
            storeFile file('eximpo-release-key.jks')
            storePassword 'Eximpo@2026'
            keyAlias 'eximpo-key'
            keyPassword 'Eximpo@2026'
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.gms:play-services-auth:20.7.0'
}
